spring:
  application:
    name: gateway
  cloud:
    config:
      enabled: true
      fail-fast: true
      retry:
        initial-interval: 4000
        max-interval: 20000
      uri: ${SPRING_CLOUD_CONFIG_URI:http://config-server:7777}
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOriginPatterns:
                  - "http://localhost:5173"
                  - "http://localhost:9090"
                  - "http://localhost:9091"
                  - "https://fit-desk.netlify.app"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
                  - OPTIONS
                  - HEAD
                allowedHeaders: "*"
                allowCredentials: true
                maxAge: 3600
          httpclient:
            connect-timeout: 10000  
            response-timeout: 60s


resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        minimumNumberOfCalls: 10
        permittedNumberOfCallsInHalfOpenState: 5
        waitDurationInOpenState: 30s
        failureRateThreshold: 80  
        slowCallRateThreshold: 80
        slowCallDurationThreshold: 30s 
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.util.concurrent.TimeoutException
          - java.io.IOException
    instances:
      billingCircuitBreaker:
        baseConfig: default
        slowCallDurationThreshold: 45s
  timelimiter:
    configs:
      default:
        timeoutDuration: 60s  
    instances:
      billingCircuitBreaker:
        baseConfig: default

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${random.uuid}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true
    registry-fetch-interval-seconds: 30

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    com.gateway.security: DEBUG
    io.github.resilience4j: DEBUG 



management:
  endpoints:
    web:
      exposure:
        include: health,info,env,gateway,metrics,loggers,circuitbreakers,httpexchanges
      base-path: /actuator
  endpoint:
    health:
      show-details: always
  info:
    env:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
  httpexchanges:
    recording:
      enabled: true

server:
  port: 9090
  netty:
    connection-timeout: 30s
    idle-timeout: 60s