spring:
  application:
    name: msvc-product

server:
  port: ${MSVC_MEMBERS_PORT:9092}

resilience4j:
  timelimiter:
    instances:
      products:
        timeoutDuration: 6s
        cancelRunningFuture: true
  circuitbreaker:
    instances:
      products:
        registerHealthIndicator: true
        slidingWindowSize: 5
        failureRateThreshold: 100
        waitDurationInOpenState: 15s
        permittedNumberOfCallsInHalfOpenState: 2
        minimumNumberOfCalls: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
  retry:
    instances:
      products:
        maxAttempts: 3 
        waitDuration: 500ms

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://eureka-server:8761/eureka}
    fetch-registry: true
    register-with-eureka: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    org.springframework.boot.autoconfigure.security: DEBUG
    org.springframework.web.cloud.openfeign: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG